package TP3.autogen;

/**
* CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* jeudi 20 mai 2021 10 h 31 WEST
*/

public interface CounterOperations 
{
  int value ();
  void inc ();
  void dec ();
} // interface CounterOperations
