package exam.autogen;

/**
* Horloge.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* jeudi 10 juin 2021 10 h 23 WEST
*/

public interface Horloge extends HorlogeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Horloge
