package exam.autogen;

/**
* HorlogeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* jeudi 10 juin 2021 10 h 23 WEST
*/

public interface HorlogeOperations 
{
  int heure ();
  int minute ();
  String GMT ();
  String GMT_PLUS_1 ();
  void setTime (int h, int m);
} // interface HorlogeOperations
