package exam.autogen;

/**
* HorlogeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* jeudi 10 juin 2021 10 h 23 WEST
*/

public final class HorlogeHolder implements org.omg.CORBA.portable.Streamable
{
  public Horloge value = null;

  public HorlogeHolder ()
  {
  }

  public HorlogeHolder (Horloge initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HorlogeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HorlogeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HorlogeHelper.type ();
  }

}
